config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :categories
  resources :photos, except: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_one_attached :cover
  has_many :photos, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :description, length: { in: 1..200 }, allow_blank: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, length: { in: 1..300 }, allow_blank: true

  belongs_to :commentable, polymorphic: true
  belongs_to :photo, counter_cache: true, optional: true

  after_create :increment_comments_count
  after_destroy :decrement_comments_count

  private

  def increment_comments_count
    return unless commentable_type == "Photo"

    commentable.increment!(:comments_count)
    # commentable.increment(:comments_count).save
  end

  def decrement_comments_count
    return unless commentable_type == "Photo"

    commentable.decrement!(:comments_count)
    # commentable.decrement(:comments_count).save
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :image
  belongs_to :category, counter_cache: true, optional: true
  has_many :comments, as: :commentable, dependent: :destroy

  validates :title, presence: true
  validates :description, length: { in: 1..200 }, allow_blank: true

  # after_create :increment_photos_count
  # after_destroy :decrement_photos_count

  # private

  # def increment_photos_count
  #   return unless photos_type == "Photo"

  #   photos.increment!(:comments_count)
  #   # photos.increment(:comments_count).save
  # end

  # def decrement_photos_count
  #   return unless photos_type == "Photo"

  #   photos.decrement!(:comments_count)
  #   # photos.decrement(:comments_count).save
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    render "index"
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
    @photos = @category.photos
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to category_path(@category)
    else
      render :new, status: :unprocessable_entity 
    end
  end

  def edit
    @category = Category.find(params[:id])

  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to category_path(@category)
    else
      render "edit", status: :unprocessable_entity 
    end
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy

    redirect_to categories_path, status: :see_other
  end
 
  private

  def category_params
    params.require(:category).permit(:name, :description, :cover)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def show
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def edit
    @photo = Photo.find(params[:id])

  end

  def create
    @photo = Photo.new(photo_params)

    if @photo.save
      redirect_to photo_path(@photo)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @photo = Photo.find(params[:id])
 
    if @photo.update(photo_params)
      redirect_to photo_path(@photo)
    else
      render "edit", status: :unprocessable_entity 
    end
  end

  def destroy
    photo = Photo.find(params[:id])
    photo.destroy

    redirect_to photos_path, status: :see_other
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :description, :category_id, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/categories/_form.html.erb
<%= form_with model: category do |form| %>
<div>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <% category.errors.full_messages_for(:name).each do |message|  %>
    <span>
      <%= message %>
    </span>
  <% end %>
</div>
<div>
  <%= form.label :description %>
  <%= form.text_area :description%>

  <% category.errors.full_messages_for(:description).each do |message|  %>
    <span>
      <%= message %>
    </span>
  <% end %>

</div>

<div>
  <%= form.submit %>
</div>

<% end %>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render "form", category: @category %>

app/views/categories/index.html.erb
<h1>Categories</h1>
  
<% @categories.each do |category| %>
<div>
  <% if category.cover.attached? %>
  <div>
    <%= image_tag category.cover, alt: "Category Cover" %>
  </div>
  <% end %>
  <span>
    <%= category.name%> 
  </span>
   <span>
    <%= category.photos_count%>
  </span>
   <span>
    <%= category.description%>
  </span>

  <%= link_to "show", category_path(category) %>
  <%= link_to "edit", edit_category_path(category) %>
  <%= link_to "destroy ", category_path(category), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %>
</div>
<% end %> 

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render "form", category: @category %>

app/views/categories/show.html.erb
<h1> <%= @category.name %> </h1>
<p> <%= @category.description %> </p>

<h2> Photos </h2>
<%= link_to "New Photo", new_photo_path %>
<br />
<br />

<% @photos.each do |photo| %>
  <div>
    <% if photo.image.attached? %>
      <div>
        <%= image_tag photo.image, alt: "Photo Image" %>
      </div>
    <% end %>
  </div>
  <p>
    <%= photo.title %> 
  </p>
   <p>
    <%= photo.comments_count %> 
  </p>
  <div>
    <%= link_to "show", photo_path(photo) %>
    <%= link_to "edit", edit_photo_path(photo) %>
    <%= link_to "destroy ", photo_path(photo), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
  </div>

<% end %>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SomesplashC10SomesplashTeam2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with model: photo do |form| %>
<div>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <% photo.errors.full_messages_for(:title).each do |message|  %>
    <span>
      <%= message %>
    </span>
  <% end %>
</div>
<div>
  <%= form.label :description %>
  <%= form.text_area :description%>

  <% photo.errors.full_messages_for(:description).each do |message|  %>
    <span>
      <%= message %>
    </span>
  <% end %>

</div>

<div>
  <%= form.label :category_id %>
  <%= form.collection_select :categoy_id, Category.order(:name), :id, :name %>

  <% photo.errors.full_messages_for(:category_id).each do |message|  %>
    <span>
      <%= message %>
    </span>
  <% end %>

</div>

<div>
  <%= form.submit %>
</div>

<% end %>

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/photos/destroy.html.erb
<h1>Photos#destroy</h1>
<p>Find me in app/views/photos/destroy.html.erb</p>

app/views/photos/edit.html.erb
<h1>Edit Photo</h1>

<%= render "form", photo: @photo %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= form_with model: @photo do |form| %>
<div>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <% @photo.errors.full_messages_for(:title).each do |message|  %>
    <span>
      <%= message %>
    </span>
  <% end %>
</div>
<div>
  <%= form.label :description %>
  <%= form.text_area :description%>

  <% @photo.errors.full_messages_for(:description).each do |message|  %>
    <span>
      <%= message %>
    </span>
  <% end %>

</div>

<div>
  <%= form.label :category_id %>
  <%= form.collection_select :categoy_id, Category.order(:name), :id, :name %>

  <% @photo.errors.full_messages_for(:category_id).each do |message|  %>
    <span>
      <%= message %>
    </span>
  <% end %>

</div>

<div>
  <%= form.submit %>
</div>

<% end %>

app/views/photos/show.html.erb
<h1> <%= @photo.title %> </h1>
<p> <%= @photo.description %> </p>

<div>
    <% if @photo.image.attached? %>
      <div>
        <%= image_tag @photo.image, alt: "Photo Image" %>
      </div>
    <% end %>
  </div>
   <p>
    <%= @photo.comments %> 
  </p>
  <div>
    <%= link_to "edit", edit_photo_path(@photo) %>
    <%= link_to "destroy ", photo_path(@photo), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
</div>

app/views/photos/update.html.erb
<h1>Photos#update</h1>
<p>Find me in app/views/photos/update.html.erb</p>